# https://lychee.cli.rs/usage/config/
exclude_path = ["node_modules", ".git"]
exclude = [
  "^https?://localhost",
  "^https?://127\\.0\\.0\\.1",
  "^https?://example\\.com"
]
accept = [200, 206, 429]
max_redirects = 5
no_progress = true
